### ISSUE TITLE
lage v2: Crash in yoga

### ISSUE THREAD

**Issue by dzearing** [microsoft/lage#559]
Test failed, but then yoga failed:

```
success: 47, skipped: 58, pending: 23, aborted: 0, failed: 1
Took a total of 31.14s to complete.D:\git\cloudpack2\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: attempted to get private field on non-instance
    at p (D:\git\cloudpack2\node_modules\@lage-run\lage\dist\lage.js:632:117800)
    at d (D:\git\cloudpack2\node_modules\@lage-run\lage\dist\lage.js:632:117957)
    at AbortSignal.P (D:\git\cloudpack2\node_modules\@lage-run\lage\dist\lage.js:632:121583)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:585:26)
    at abortSignal (node:internal/abort_controller:284:10)
    at AbortController.abort (node:internal/abort_controller:315:5)
    at u.onFail (D:\git\cloudpack2\node_modules\@lage-run\lage\dist\lage.js:632:127832)
    at u.run (D:\git\cloudpack2\node_modules\@lage-run\lage\dist\lage.js:632:129480)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Repro is to have a jest test fail.

**Comment by kenotron** [comment]
We got rid of yoga, yay!!
